<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Add Edit Form') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <p>
                        Below is a Livewire Component which display the Listing of Products along with the Option to Add and Edit, which opens up the Form in a Modal. You can select the Fields that you want to display in Add and Edit Form. You can also select the Type of each Field as well as set the Validation for each Field.
                    </p>

                    <p class="mt-4">The Example also show how to update a Belongs To Field. If you are interested in checking how to create a Form with Belongs To Many Relation check this <a href="{{route('belongs-to-many-form')}}" class="cursor-pointer text-blue-500">example</a>.</p>

                    <p class="mt-4">You can check the Code of the Livewire Component which has been generated by the Package on <a href="https://github.com/ascsoftw/tall_crud_example/tree/add-edit" class="cursor-pointer text-blue-500">Github</a>.</p>

                    <p class="mt-4">You can generate a similar Component by Selecting the Appropriate Settings at <a href="{{route('crud-generator')}}" class="cursor-pointer text-blue-500">Crud Generator Menu</a>.</p>

                    <p class="my-4">If you are interested in the Video Tutorial, you can check this Video which generates the following Livewire Component on <a href="https://youtu.be/z_lvH-DsknU" class="cursor-pointer text-blue-500">Youtube</a>.</p>
                    @livewire('products')
                </div>
            </div>
        </div>
    </div>
</x-app-layout>