<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Eager Load') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">

                    <p>
                        We have a Relationship as <span class="font-bold">Product BelongsTo Brand</span>. Below is a Livewire Component which display the Listing of Products and also display the Brand Name by Eager Loading it.
                    </p>
                    <p class="mt-4">You can check the Code of the Livewire Component which has been generated by the Package on <a href="https://github.com/ascsoftw/tall_crud_example/tree/eager-load" class="cursor-pointer text-blue-500">Github</a>.</p>

                    <p class="mt-4">You can generate a similar Component by Selecting the Appropriate Settings at <a href="{{route('crud-generator')}}" class="cursor-pointer text-blue-500">Crud Generator Menu</a>.</p>

                    <p class="my-4">If you are interested in the Video Tutorial, you can check this Video which generates the following Livewire Component on <a href="https://youtu.be/eDe0hb5-xUY" class="cursor-pointer text-blue-500">Youtube</a>.</p>

                    @livewire('eager-load')
                </div>
            </div>
        </div>
    </div>
</x-app-layout>